spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://192.168.99.101/customerapi
    username: dbuser
    password: dbpass

logging:
  level:
    root: INFO

---
spring.config.activate.on-profile: dev

logging:
  level:
    root: DEBUG

---
spring.config.activate.on-profile: prod

logging:
  file:
    path: /tmp/
    name: customerapi.log
  level:
    root: WARN
